apiVersion: v1
kind: Service
metadata:
  name: testcarolmesqu-azure-kubernetes-service
  labels:
    app: testcarolmesqu-azure-kubernetes-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: testcarolmesqu-azure-kubernetes-service